= How to get a list of policy features
:attribute-missing: drop

When creating API policies we need to provide access to features (end points).
The names of these features refer to the operation id of the end point.
In this guide we'll learn how to extract a list of these features and their mapping to API end points.

== Pre Requisites

This guide assumes that you have followed created a LUSID account, as covered in the  xref:tutorials/getting-started.adoc[] guide.

You'll also need to download the https://stedolan.github.io/jq/[jq command line tool^].

== Download Swagger file

First you'll need to download the Swagger file for your domain.
You can find this at `https://<yourname>.lusid.com/api/swagger/v0/swagger.json`

[source, bash]
----
wget https://<yourname>.lusid.com/api/swagger/v0/swagger.json
----

[NOTE]
====
The next part of this guide assumes that this file is downloaded to a local file named `swagger.json`.
====

== Query Swagger file

Now let's query that Swagger file using the jq command line tool.
You can get a list of operation ids and descriptions for every end point by running the following command:

[source, bash]
----
cat swagger.json | jq -r '.paths | keys[] as $k | [
    (.[$k] |
     keys[] as $k1 |
     [$k, .[$k1].operationId, .[$k1].summary]
    )
  ] | .[]'
----

This returns a lot of results.
If you want to return just the first 10 end points, you can run the following command:

[source, bash]
----
cat swagger.json | jq -r '.paths | keys[] as $k | [
    (.[$k] |
     keys[] as $k1 |
     [$k, .[$k1].operationId, .[$k1].summary]
    )
  ] | .[]' |
head -n 40
----

If we run that, we'll see the following output:

.Features / API points
[source, json]
----
[
  "/api/aggregation/$valuation",
  "GetValuation",
  "[BETA] Perform valuation for a list of portfolios and/or portfolio groups"
]
[
  "/api/aggregation/$valuationinlined",
  "GetValuationOfWeightedInstruments",
  "[BETA] Perform valuation for an inlined portfolio"
]
[
  "/api/aggregation/{scope}/{code}/$generateconfigurationrecipe",
  "GenerateConfigurationRecipe",
  "[EXPERIMENTAL] Generates a recipe sufficient to perform valuations for the given portfolio."
]
[
  "/api/allocations",
  "ListAllocations",
  "[EXPERIMENTAL] List Allocations"
]
[
  "/api/allocations",
  "UpsertAllocations",
  "[EXPERIMENTAL] Upsert Allocations"
]
[
  "/api/allocations/{scope}/{code}",
  "DeleteAllocation",
  "[EXPERIMENTAL] Delete allocation"
]
[
  "/api/allocations/{scope}/{code}",
  "GetAllocation",
  "[EXPERIMENTAL] Get Allocation"
]
[
  "/api/calendars/businessday/{scope}/{code}",
  "IsBusinessDateTime",
  "[EXPERIMENTAL] Check whether a DateTime is a \"Business DateTime\""
]
----

=== CSV file of all endpoints

We could also generate a CSV file of all endpoints by running the following code:

[source, bash]
----
cat swagger.json | jq -r '.paths | keys[] as $k | [
    (.[$k] |
     keys[] as $k1 |
     [($k |  gsub("{"; "\\{") | gsub("}"; "\\}")), $k1, .[$k1].operationId, .[$k1].summary]
    )
  ] | .[] | @csv' \
> swagger.csv
----

.swagger.csv
[format="csv", options="header", cols="35,10,25,30", role="word-wrap"]
|===
End point, Method, Feature Name, Description
include::example$entitlements/swagger.csv[]
|===
