= LUSID

LUSID by FINBOURNE is a bi-temporal investment management data platform with portfolio accounting capabilities.
The content in these guides is organised into the following sections:


xref:tutorials/index.adoc[Tutorials] ::
Take you through a series of steps showing how to accomplish basic tasks with LUSID.
Start here if you're new to LUSID.

xref:how-to/index.adoc[How-To Guides] ::
Recipes for how to accomplish common tasks with LUSID.
They are more advanced than tutorials and assume some knowledge of how LUSID works.

xref:reference/index.adoc[Reference] ::
Contain API documentation for LUSID.

xref:explanation/index.adoc[Explanation] ::
Provide background information and explanation of LUSID's core concepts.



////
== Getting Started

These guides will help you get up and running with LUSID.

== Common Tasks

Use case specific content
https://support.lusid.com/knowledgebase/article/KA-01828/

Examples of tutorials:
https://www.lusid.com/app/resources/tutorials/getting-started/ibor/upload-transactions#api

Derived Portfolios
https://github.com/finbourne/sample-notebooks/blob/master/examples/use-cases/risk-and-performance/Backtesting%20with%20LUSID%20derived%20portfolios.ipynb
https://support.lusid.com/knowledgebase/article/KA-01853
https://github.com/finbourne/sample-notebooks/blob/develop/examples/features/core-lusid/Derived%20portfolios.ipynb

== LUSID Architecture

== Glossary / Terminology

////
