= Python
:description: This guide covers the Python SDK for LUSID by FINBOURNE and other Python tools.

This guide will help you get started with building applications with LUSID by FINBOURNE and the Python programming language.

FINBOURNE develops and maintains two versions of the LUSID® Python SDK:

https://github.com/finbourne/lusid-sdk-python[lusid-sdk-python^] ::
supports `Production` and `Early Access` API endpoints
https://github.com/finbourne/lusid-sdk-python-preview[lusid-sdk-python-preview^] ::
supports `Production`, `Early Access`, `Beta` and `Experimental` API endpoints.

include::partial$api-endpoints.adoc[]

[NOTE]
====
You should only use `lusid-sdk-python-prevew` if you want to use the `Beta` or `Experimental` API endpoints.
====

== Installation

The SDK is available on PyPi and can be installed by running the following:

[source, bash]
----
pip install lusid-sdk
----

The preview version of the SDK can be installed by running the following:

[source, bash]
----
pip install lusid-sdk-preview
----

[WARNING]
====
If you install both `lusid-sdk-python` and `lusid-sdk-python-preview`, `import lusid` will refer to `lusid-sdk-python`. 
====

== Configuring API Client

Now that you've installed the SDK, it's time to use it. 
First, import the following modules:

[source, python]
----
include::example$getting-started/hello_world.py[tag="lusid-imports"]
----

You can create the API factory by running the following code:

[source, python]
----
include::example$getting-started/hello_world.py[tag="create-client-factory"]
----

include::partial$credentials.adoc[]

Now that the API client is ready, you are ready to use the various API endpoints. 
You can list all the API endpoints by running the following:

[source, python]
----
[api for api in dir(lusid.api) if "API" in api]
----

An API endpoint can be constructed by calling `api_factory.build(lusid.api.<className>)` for any of the returned classes.
For example, to construct the Transactions Portfolio API, run the following:

[source, python]
----
include::example$getting-started/hello_world.py[tag="create-tx-portfolios-api"]
----

For a worked example showing how to use the Python SDK for a simple workflow, see xref:lusid:get-started/quick-start.adoc[].

== API Documentation

For reference documentation on each of the API endpoints, see https://lusid-sdk-python.readthedocs.io/en/latest/_autosummary/sdk.lusid.api.html#module-sdk.lusid.api[Python SDK Reference Documentation^].

== Other Tools

The following are other Python based tools:

https://github.com/finbourne/sample-notebooks[sample-notebooks^]::
Jupyter Notebooks that use the Python SDK to walk through common use cases.

https://github.com/finbourne/lusid-python-tools[lusid-python-tools^]::
Python tools for LUSID.