= How to configure a secrets file
:description: This guide walks through how to configure the secrets file that contains credentials for the LUSID API.
:page-pagination: true

In this guide you will create a secrets file for use with the LUSID API and LUSID SDKs.
The LUSID SDKs all support credentials defined in a secrets file or as xref:how-to/connecting-to-lusid/setup-environment-variables.adoc[environment variables].
You can choose whichever approach better suits your circumstances.

== Pre Requisites

You'll need to have created a LUSID application before following the instructions in this guide.
If you haven't yet created an application, see xref:how-to/connecting-to-lusid/create-application.adoc[].

== Configuring a secrets file

include::partial$credentials/get-credentials.adoc[tag="how-to-download"]

Now you'll need to create a JSON file based on these values.

.secrets.json
[source, json]
----
{
  "api" : {
    "apiUrl": "<1>",
    "tokenUrl": "<2>",
    "clientId": "<3>",
    "clientSecret": "<4>",
    "applicationName": "<applicationName>",
    "username": "<username>",
    "password": "<password>"
  }
}
----

.Web App -> JSON File mappings
[opts="header", cols="2,2,2,3"]
|===
|  JSON key | LUSID web app | Token | Description
|  `apiUrl` | `API Url` |       `<1>` | LUSID API URL
|  `tokenUrl` | `Token Url` |   `<2>` |  Okta endpoint to generate authentication token
|  `clientId` | `Client Id` |   `<3>` |  OpenID Connect Client ID
|  `clientSecret` | `Secret` |  `<4>` |   OpenID Connect Client Secret
|  `applicationName` | N/A | `<applicationName>` |  An optional identifier for your application
|  `username` | N/A | `<username>` |  Username of the account accessing the API (e.g. email used in xref:tutorials/getting-started.adoc[])
|  `password` | N/A | `<password>` |  Password of the account accessing the API (e.g. password used in xref:tutorials/getting-started.adoc[])
|===

include::partial$credentials/get-credentials.adoc[tag="production-users-tip"]
