= How to create an API Factory
:description: In this guide we'll create an API factory that can be used to connect to LUSID.

{description}


== Pre Requisites

You'll need to have created a LUSID application before following the instructions in this guide.
If you haven't yet created an application, see xref:how-to/connecting-to-lusid/create-application.adoc[].

== Setup

We'll be using the https://github.com/finbourne/lusid-sdk-python-preview[LUSID Python Preview SDK^], which you can install by running the following:

[source, bash]
----
pip install lusid-sdk-preview
----

Once you've got that installed, import the following modules:

[source, python, indent=0]
----
include::example$lusid_utils.py[tag="imports"]
----

== Using a secrets file

You can then create an API factory from a secrets file:

include::partial$api-factory.adoc[]

== Using environment variables

Or you can create an API factory from environment variables:

[source, python, indent=0]
----
include::example$lusid_utils.py[tag="api-factory-env-variables"]
----

[NOTE]
====
You will need to create environment variables containing your LUSID credentials.
For instructions on how to do this, see xref:how-to/connecting-to-lusid/setup-environment-variables.adoc[].
====


== Testing the connection

Once you've done this, it's time to check if you can connect to LUSID.
LUSID comes with some pre-loaded data, which includes financial instruments.
These can be returned from the Instruments API.

You can return the first 10 of these instruments by running the following code:

[source, python]
----
instruments_api = api_factory.build(lusid.api.InstrumentsApi)
instruments_api.list_instruments(limit=10)
----

If you get back some results, you have successfully connected to LUSID!


