= Connecting to LUSID

// {docdatetime}

In this series of guides you will go through the steps to get you connected to LUSID by FINBOURNE, a bi-temporal investment management data platform with portfolio accounting capabilities.

== Pre Requisites

These guides assume that you have already created and logged into your LUSID account.
For more details, see the xref:tutorials/getting-started.adoc[] guide.

== Connecting to LUSID

The guides below go through tasks for connecting to LUSID from the language SDKs:

xref:ROOT:how-to/connecting-to-lusid/create-application.adoc[] ::
Create a LUSID application to use with the language SDKs.

Then follow the steps in one of the guides below, depending on which approach you prefer to take for storing LUSID credentials:

xref:ROOT:how-to/connecting-to-lusid/configure-secrets-file.adoc[] ::
Set up your credentials in a secrets file for use with the language SDKs.

xref:ROOT:how-to/connecting-to-lusid/setup-environment-variables.adoc[] ::
Set up your credentials in environment variables for use with the language SDKs.

Finally, follow the guide below to connect to LUSID:

xref:ROOT:how-to/connecting-to-lusid/create-api-factory.adoc[] ::
Set up your credentials in environment variables for use with the language SDKs.
