= How to set up environment variables
:description: In this guide you will set up LUSID credentials in environment variables for use with the LUSID SDKs.
:page-pagination: true

In this guide you will set up LUSID credentials in environment variables for use with the LUSID API and LUSID SDKs.
The LUSID SDKs all support credentials defined as environment variables or in a xref:how-to/connecting-to-lusid/configure-secrets-file.adoc[secrets file].
You can choose whichever approach better suits your circumstances.

== Pre Requisites

You'll need to have created a LUSID application before following the instructions in this guide.
If you haven't yet created an application, see xref:how-to/connecting-to-lusid/create-application.adoc[].

== Setting up environment variables

include::partial$credentials/get-credentials.adoc[tag="how-to-download"]

You can then define the following environment variables:

include::partial$credentials/auth-mapping.adoc[]

include::partial$credentials/get-credentials.adoc[tag="production-users-tip"]

For more details on how to set environment variables, see:

* https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1[Setting environment variables in Windows^]
* https://linuxize.com/post/how-to-set-and-list-environment-variables-in-linux/[How to Set and List Environment Variables in Linux^]
