= How to create a derived portfolio
:description: In this guide we'll create a derived portfolio, which can be used to do pre-trade and post-trade what-if analysis.

A derived portfolio is a copy of an existing portfolio.
A derived transaction portfolio inherits all holdings and transactions from its parent transaction portfolio.

Changes made to the parent portfolio are automatically reflected in the derived portfolio, but the derived portfolio can also contain its own additional transactions that take precedence over the parent portfolio's transactions.

[TIP]
====
Derived portfolios in conjunction with scopes are a powerful construct.
For example, to do pre-trade what-if analysis, a derived portfolio could be created in a new namespace linked to the underlying live (parent) portfolio in the ‘official’ scope.
Scenario transactions can then be booked in the derived portfolio, and the performance of the two could be compared without affecting the live book.
====

== Pre Requisites

This guide assumes that you have created a transaction portfolio with the code `uk-portfolio-code`.
For more details, see the xref:how-to/load-transaction-portfolio.adoc[] guide.

== Setup

You'll need to import the following modules into your Python script:

[source, python]
----
include::example$portfolios/test_portfolios.py[tag="imports-lusid"]
include::example$portfolios/test_portfolios.py[tag="imports-dates"]
----

You can specify your own scope and portfolio code by updating the line below:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="scope"]
include::example$portfolios/test_portfolios.py[tag="uk-portfolio-code"]
----

== Initialise API

Initialise the Derived Transaction Portfolios API:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="derived-api"]
----

== API call

You can create a derived portfolio by running the following code:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="derived-portfolio-code"]

include::example$portfolios/test_portfolios.py[tag="create-derived-portfolio"]
----
