= How to get the default transaction types
:description: In this guide we'll learn how to return LUSID's built-in transaction types.

LUSID comes pre-loaded with some commonly used transaction types.
In this guide you will learn how to return those types.

The code and data used in this guide can be downloaded from the {examples-repository}[examples^] section of the LUSID Python Tools repository.
The code is in the {examples-repository-base}/test_configure_transaction_types.py[test_configure_transaction_types.py^] file, and the data under {examples-repository-base}/data/test_configure_transaction_types[data/test_configure_transaction_types^].

== Setup

This guide assumes that you have followed the xref:how-to/get-started/index.adoc[] guides and have successfully connected to LUSID.

You will need to import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
----

== List transaction types

The list of configured transaction types are available via the System Configuration API:

[source, python, indent=0]
----
include::example$transaction-types/test_configure_transaction_types.py[tag="create-apis"]
----

You can return a list of them by running the following code:

[source, python, indent=0]
----
include::example$transaction-types/test_configure_transaction_types.py[tag="get-transaction-types"]
----

.Default Transaction Types
[format="csv", options="header"]
|===
include::example$transaction-types/transaction_types.csv[]
|===

As you can see, there are lots of different transaction types, covering a variety of use cases.
But if you use a transaction type that isn't on this list, you can add new transaction types.
For more details, see xref:ROOT:how-to/configure-transaction-types.adoc[].
