= How to get a valuation with a default recipe

The code and data used in this guide can be downloaded from the {examples-repository}[examples^] section of the LUSID Python Tools repository.
The code is in the {examples-repository-base}/test_valuation.py[test_valuation.py^] file, and the data under {examples-repository-base}/data/test_valuation[data/test_valuation^].

[source, python, indent=0]
----
include::example$valuation/test_valuation.py[tag="imports"]
----

== Compute valuation

LUSID comes with a default recipe that computes the valuation of a portfolio

You can compute the number of units of an instrument held on a specific date with their present value and present value as a proportion using the following function:
[source, python, indent=0]
----
include::example$valuation/test_valuation.py[tag="compute-valuation"]
----

=== Valuation on 21st April 2021

Let's run this function as of 21st April 2021:

[source, python, indent=0]
----
include::example$valuation/test_valuation.py[tag="get-valuation-20210421"]
----

.Valuation on 21st April 2021
[format="csv", options="header"]
|===
include::example$valuation/valuation-20210421.csv[]
|===

=== Valuation on 22nd April 2021

[source, python, indent=0]
----
include::example$valuation/test_valuation.py[tag="get-valuation-20210422"]
----

.Valuation on 22nd April 2021
[format="csv", options="header"]
|===
include::example$valuation/valuation-20210422.csv[]
|===