= How to get the default transaction types
:description: In this guide we'll learn how to return LUSID's built-in transaction types.

LUSID comes pre-loaded with some commonly used transaction types.
In this guide you will learn how to return those types.

The code and data used in this guide can be downloaded from the {examples-repository}[examples^] section of the LUSID Python Tools repository.
The code is in the {examples-repository-base}/test_configure_transaction_types.py[test_configure_transaction_types.py^] file, and the data under {examples-repository-base}/data/test_configure_transaction_types[data/test_configure_transaction_types^].

== Setup

We'll be using the https://github.com/finbourne/lusid-python-tools[LUSID Python Tools library^] in this guide, which you can install by running the following:

[source, bash]
----
pip install lusidtools
----

Once you've got that installed, import the following modules:

[source, python, indent=0]
----
include::example$transaction-types/test_configure_transaction_types.py[tag="imports"]
----

And then create an API factory:

include::partial$api-factory.adoc[]

== List transaction types

The list of configured transaction types are availabled via the System Configuration API.
You can return a list of them by running the following code:

[source, python, indent=0]
----
include::example$transaction-types/test_configure_transaction_types.py[tag="create-apis"]

include::example$transaction-types/test_configure_transaction_types.py[tag="get-transaction-types"]
----

.Default Transaction Types
[format="csv", options="header"]
|===
include::example$transaction-types/transaction_types.csv[]
|===

As you can see, there are lots of different transaction types, covering a variety of use cases.
But if you use a transaction type that isn't on this list, you can add new transaction types.
For more details, see xref:lusid:how-to/configure-transaction-types.adoc[].