= How to load transactions
:description: In this guide we'll learn how to import transactions into LUSID.

{description}
A transaction is an economic change to a portfolio.
Transactions can be one-sided (e.g. cash inflow) or two-sided (e.g. an equity trade purchasing stock and settling cash).

The code and data used in this guide can be downloaded from the {examples-repository}[examples^] section of the LUSID Python Tools repository.
The code is in the {examples-repository-base}/test_ibor.py[test_ibor.py^] file, and the data under {examples-repository-base}/data/test_ibor[data/test_ibor^].

== Pre Requisites

This guide assumes that you have followed the xref:how-to/get-started/index.adoc[] guides and have successfully connected to LUSID.
This guide uses the portfolio created in xref:ROOT:how-to/load-transaction-portfolio.adoc[], and the instruments loaded in  xref:ROOT:how-to/maintain-instruments-master.adoc[].

== Setup

You will need to import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
include::example$ibor/test_ibor.py[tag="imports-dates"]
----

You can specify your own scope and portfolio code by updating the line below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="scope-portfolio-code"]
----

And then initialise the Transactions Portfolio API:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="create-portfolio-api"]
----

== Our Transactions

We have details of transactions, and their accompanying instruments in a CSV file described below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="transactions-file"]
include::example$ibor/test_ibor.py[tag="load-transactions"]
----

.Transactions
[format="csv", options="header"]
|===
include::example$ibor/transactions.csv[]
|===

== Import Transactions

Let's import the transactions.
For the transaction that loads cash into our portfolio we need to use a different identifier than for the shares.
For more information about instrument identifiers, see xref:ROOT:how-to/instrument-identifiers.adoc[].

You can import transactions using the code below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="import-transactions"]
----

== Get Transactions

Now let's retrieve those transactions.
We'll format the response using the following function:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="format-transactions"]
----

You can get the transactions using the Get Transactions API, as shown below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-transactions"]
----

.Transactions
[format="csv", options="header", cols="20,20,30,10,10"]
|===
include::example$ibor/transactions_response.csv[]
|===
