= How to load quotes/market data
:description: In this guide we'll learn how to load quotes into LUSID's built-in quote store.

{description}
This store is used to record market data that can be used to value holdings and run other analyses.
It can be used to store market prices, rates, and FX quotes.

The code and data used in this guide can be downloaded from the {examples-repository}[examples^] section of the LUSID Python Tools repository.
The code is in the {examples-repository-base}/test_ibor.py[test_ibor.py^] file, and the data under {examples-repository-base}/data/test_quotes[data/test_ibor^].

== Pre Requisites

This guide assumes that you have imported the instruments described in xref:how-to/maintain-instruments-master.adoc[].

You will need to import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
include::example$ibor/test_ibor.py[tag="imports-dates"]
----

You can specify your own scope and portfolio code by updating the line below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="scope-portfolio-code"]
----

And then initialise the Quotes and Instruments APIs:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="quotes-api"]
include::example$ibor/test_ibor.py[tag="instruments-api"]
----

== Our Quotes

The file below contains end of day quotes for the Amazon, Apple, and CoinBase instruments from 21st April 2021 to 23rd April 2021:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="quotes-file"]
include::example$ibor/test_ibor.py[tag="load-quotes"]
----

.Quotes
[format="csv", options="header"]
|===
include::example$ibor/quotes.csv[]
|===

When loading quotes we need to make sure that the Provider, Instrument ID, Instrument ID Type, Quote Type, and Field properties match those expected by the recipe that we use to xref:how-to/get-valuation-default-recipe.adoc[value the portfolio].

The default recipe that comes with LUSID expects quotes to be loaded by their Lusid Instrument ID.
We don't know what that is for the instruments described above, but we can find it out using the Instruments API:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="load-quotes-get-luid"]
----

.Quotes with LUID
[format="csv", options="header"]
|===
include::example$ibor/quotes_with_luid.csv[]
|===

== Import Quotes

You can import these quotes into LUSID by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="import-quotes"]
----

[NOTE]
====
The field value used when loading quotes is case-insensitive and is used when xref:how-to/get-valuation-default-recipe.adoc[valuing a portfolio].
====
