= How to load quotes/market data
:description: In this guide we'll learn how to load quotes into LUSID's built-in quote store.

In this guide we'll learn how to load xref:reference/quotes[quotes] into LUSID's built-in quote store.

include::partial$ibor-code.adoc[]

== Pre Requisites

This guide assumes that you have imported the instruments described in xref:how-to/maintain-instruments-master.adoc[].

== Setup

Import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
include::example$ibor/test_ibor.py[tag="imports-dates"]
----

You can specify your own scope and portfolio code by updating the line below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="scope"]
include::example$ibor/test_ibor.py[tag="portfolio-code"]
----

== Initialise API

Initialise the Quotes and Instruments APIs:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="quotes-api"]
include::example$ibor/test_ibor.py[tag="instruments-api"]
----

== Our Quotes

The file below contains end of day quotes for the Amazon, Apple, and CoinBase instruments from 21st April 2021 to 23rd April 2021:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="quotes-file"]
include::example$ibor/test_ibor.py[tag="load-quotes"]
----

.Quotes
[format="csv", options="header"]
|===
include::example$ibor/quotes.csv[]
|===

When loading quotes we need to make sure that the Provider, Instrument ID, Instrument ID Type, Quote Type, and Field properties match those expected by the recipe that we will use to xref:how-to/valuation/get-valuation-default-recipe.adoc[value the portfolio].

The default recipe that comes with LUSID expects quotes to be loaded by their Lusid Instrument ID.
We don't know what that is for the instruments described above, but we can find it out using the Instruments API:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="load-quotes-get-luid"]
----

.Quotes with LUID
[format="csv", options="header"]
|===
include::example$ibor/quotes_with_luid.csv[]
|===

== API call

You can import these quotes into LUSID by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="import-quotes"]
----

[NOTE]
====
The field value used when loading quotes is case-insensitive and is used when xref:how-to/valuation/get-valuation-default-recipe.adoc[valuing a portfolio].
====
