= How to maintain an instruments master
:description: In this guide we will learn how to maintain an instruments master in LUSID by FINBOURNE.

In this guide we will learn how to maintain an instruments master.
Instruments in LUSID are used to represent financial assets that you own or have exposure to.
We'll start by importing some instruments, then we'll retrieve them, update them, and finally delete them.

include::partial$ibor-code.adoc[]

== Pre Requisites

This guide assumes that you have followed the xref:how-to/connecting-to-lusid/index.adoc[] guides and have successfully connected to LUSID.

== Setup

Import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
include::example$ibor/test_ibor.py[tag="imports-dates"]
----

== Initialise API

Initialise the Instruments API:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="instruments-api"]
----

== Our Instruments

Before we import our instruments into LUSID, let's have a look at what we have.
Our instruments are stored in a CSV file, so we'll first load that into a Pandas DataFrame:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="instruments-file"]
include::example$ibor/test_ibor.py[tag="load-instruments"]
----

.instruments
[format="csv", options="header"]
|===
include::example$ibor/instruments.csv[]
|===

We've got a mix of equities and government bonds.

== Upsert instruments

Let's import those instruments into LUSID.

Any instrument imported into LUSID must have at least one unique identifier.
A list of valid identifiers is described in xref:how-to/instrument-identifiers.adoc[].
Each of our instruments has a Figi and ClientInternal identifier, so we will use both of those as identifiers.

We'll need to do some mapping between the column names in our DataFrame and those expected by the LUSID API.
`client_internal` becomes `ClientInternal` and `figi` becomes `Figi`.

You can import the instruments by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="import-instruments"]
----

The results from importing these instruments are converted into the Pandas DataFrame shown below:

.LUIDs
[format="csv", options="header"]
|===
include::example$ibor/luids.csv[]
|===

The extra thing added is the `LUID` column, which contains a https://support.lusid.com/knowledgebase/article/KA-01861/en-us[LUSID Unique Instrument Identifier^].

== Get instruments by identifier

We can get back instruments by any of the identifiers that we used when upserting the instruments.
To recap, we imported the `Figi` and `ClientInternal` identifiers for each instrument.

To retrieve the Amazon instrument by Figi, run the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-instrument"]
----

.Instrument by FIGI
[format="csv", options="header"]
|===
include::example$ibor/get_instrument.csv[]
|===

To retrieve the Amazon instrument by Client Internal code, run the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-instrument-client-internal"]
----

.Instrument by Client Internal
[format="csv", options="header"]
|===
include::example$ibor/get_instrument_client_internal.csv[]
|===

We can also retrieve more than one instrument at the same time.
To retrieve the Amazon and CoinBase instruments by Figi, run the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-instruments"]
----

.Instruments by FIGI
[format="csv", options="header"]
|===
include::example$ibor/get_instruments.csv[]
|===


== Upsert instrument properties

In addition to the unique identifier and aliases, we can also add properties to our instruments.
For example, we might want to store the asset class for each instrument.

To define a property we need to first create a property definition.
Every property has a data type, which is specified via the `data_type_id` parameter.
Asset class is a string, so you can create a string property by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="create-property"]
----

And now add this property to each of our instruments:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="upsert-properties"]
----

== Search instruments

We can search for instruments based on property values using the Search API.
For example, to find all instruments with the `equity` asset class, run the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="search-instrument"]
----

.Equity Instruments
[format="csv", options="header"]
|===
include::example$ibor/search_instruments.csv[]
|===

== Update instrument identifier

We can also update an instrument's identifiers.
For example, to change the `ClientInternal` identifier for Amazon effective as of 6th May 2021, you can run the following:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="update-instrument-identifier"]
----

[NOTE]
====
The instrument identifier change applies from the `effective_at` time.
If none is provided it applies from now.
====

Since we've specified that the identifier change should happen on 6th May 20201, it means that if we look up the instrument with an earlier effective at date, we won't see a change.
You can see this by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-instruments-now"]
----

.Instrument identifiers before ClientInternal change
[format="csv", options="header"]
|===
include::example$ibor/get_instruments_now.csv[]
|===

But if we get the instrument with an effective date of 6th May 2021:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-instruments-later"]
----

.Instrument identifiers after ClientInternal change
[format="csv", options="header"]
|===
include::example$ibor/get_instruments_later.csv[]
|===

As we can see, the `ClientInternal` has been updated, while, as expected, the `Figi` and `LUID` stayed the same.

== Delete instruments

And finally, we can delete instruments.
To delete all instruments based on their Figi, run the following:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="delete-instruments"]
----

[NOTE]
====
When we delete an instrument it becomes unavailable from the time that we delete it onwards, but it's not permanently deleted from the system.
If we look back in time at our instruments or transactions based on those instruments, we will still be able to find them.
====
