= How to set holdings

:description: In this guide we'll set the holdings of a transaction portfolio.

{description}
We might want to do this if we have a set of positions, but don't have transaction data to create those positions.
LUSID will automatically construct adjustment transactions based on the holdings we provide.

The code and data used in this guide can be downloaded from the {examples-repository}[examples^] section of the LUSID Python Tools repository.
The code is in the {examples-repository-base}/test_ibor.py[test_ibor.py^] file, and the data under {examples-repository-base}/data/test_ibor[data/test_ibor^].

== Pre requisites

This guide assumes that you have xref:how-to/load-transaction-portfolio.adoc[created a transaction portfolio] and imported the instruments described in xref:how-to/maintain-instruments-master.adoc[].

== Setup

You will need to import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
include::example$ibor/test_ibor.py[tag="imports-dates"]
----

You can specify your own scope and portfolio code by updating the line below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="scope-portfolio-code"]
----

Setting holdings is done using the Transaction Portfolios API.
You can initialise this API end point by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="set-holdings-api"]
----

== Our Holdings

We have holdings of three instruments stored in the following CSV file:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="holdings-file"]
include::example$ibor/test_ibor.py[tag="load-holdings"]
----

.Holdings
[format="csv", options="header"]
|===
include::example$ibor/holdings.csv[]
|===

From this table, we can see that our portfolio holds 100 units of Amazon stock, 300 units of Apple, and 500 units of CoinBase.
In this guide we aren't interested in the amount that it cost us to buy these instruments.

== Set Holdings

There are two ways to set the holdings on a portfolio:

* SetHoldings: *replaces a portfolio's current holdings* with the supplied holdings.
Holdings in instruments that are not included in the supplied holdings will be removed (i.e. reduced to zero).

* AdjustHoldings: *augments a portfolio's current holdings* with the supplied holdings.
Holdings in instruments that are not included in the supplied holdings are left untouched.

To set the holdings on a transaction portfolio, use the `set_holdings` function, as shown below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="set-holdings"]
----

To adjust the holdings on a transaction portfolio, use the `adjust_holdings` function, as shown below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="adjust-holdings"]
----
