= How to create a derived portfolio
:description: In this guide we'll create a derived portfolio, which can be used to do pre-trade and post-trade what-if analysis.

In this guide we'll create a xref:reference/portfolio/derived-portfolio.adoc[derived portfolio], which can be used to do pre-trade and post-trade what-if analysis.


[NOTE.code]
====
The code used in this guide can be downloaded from the {examples-repository}[examples^] section of the LUSID Python Tools repository.
It is in the {examples-repository-base}/test_portfolios.py[test_portfolios.py^] file.
====

== Pre Requisites

This guide assumes that you have created a transaction portfolio with the code `uk-equities-trading`.
For more details, see the xref:how-to/portfolios/load-transaction-portfolio.adoc[] guide.

== Setup

Import the following modules into your Python script:

[source, python]
----
include::example$portfolios/test_portfolios.py[tag="imports-lusid"]
include::example$portfolios/test_portfolios.py[tag="imports-dates"]
----

You can specify your own scope and portfolio code by updating the line below:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="scope"]
include::example$portfolios/test_portfolios.py[tag="uk-portfolio-code"]
----

== Initialise API

Initialise the Derived Transaction Portfolios API:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="derived-api"]
----

== API call

You can create a derived portfolio by running the following code:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="derived-portfolio-code"]

include::example$portfolios/test_portfolios.py[tag="create-derived-portfolio"]
----
