= How to create a reference portfolio

In this guide we'll create a xref:reference/portfolio/reference-portfolio.adoc[reference portfolio].

[NOTE.code]
====
The code used in this guide can be downloaded from the {examples-repository}[examples^] section of the LUSID Python Tools repository.
It is in the {examples-repository-base}/test_portfolios.py[test_portfolios.py^] file.
====


== Pre Requisites

This guide assumes that you have followed the xref:how-to/connecting-to-lusid/index.adoc[] guides and have successfully connected to LUSID and xref:how-to/connecting-to-lusid/create-api-factory.adoc[created an API factory].

== Setup

Import the following modules into your Python script:

[source, python]
----
include::example$portfolios/test_portfolios.py[tag="imports-lusid"]
include::example$portfolios/test_portfolios.py[tag="imports-dates"]
----

You can specify your own scope and portfolio codes by updating the line below:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="scope"]
include::example$portfolios/test_portfolios.py[tag="reference-portfolio-code"]
----

== Initialise API

Initialise the Portfolio Groups API:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="create-reference-portfolio-api"]
----

== API calls

You can create a portfolio group by running the following code:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="create-reference-portfolio"]
----
