= How to create a portfolio group
:description: In this guide we'll create a portfolio group. Portfolio groups are used for grouping and aggregating portfolios.

In this guide we'll create a xref:reference/portfolio/portfolio-group.adoc[portfolio group].

[NOTE.code]
====
The code used in this guide can be downloaded from the {examples-repository}[examples^] section of the LUSID Python Tools repository.
It is in the {examples-repository-base}/test_portfolios.py[test_portfolios.py^] file.
====


== Pre Requisites

This guide assumes that you have created transaction portfolio with the codes `uk-equities-trading` and `us-equities-trading`.
For more details, see the xref:how-to/portfolios/load-transaction-portfolio.adoc[] guide.

== Setup

Import the following modules into your Python script:

[source, python]
----
include::example$portfolios/test_portfolios.py[tag="imports-lusid"]
include::example$portfolios/test_portfolios.py[tag="imports-dates"]
----

You can specify your own scope and portfolio codes by updating the line below:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="scope"]
include::example$portfolios/test_portfolios.py[tag="uk-portfolio-code"]
include::example$portfolios/test_portfolios.py[tag="us-portfolio-code"]
----

== Initialise API

Initialise the Portfolio Groups API:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="portfolio-groups-api"]
----

== API calls

You can create a portfolio group by running the following code:

[source, python, indent=0]
----
include::example$portfolios/test_portfolios.py[tag="creation-date"]
include::example$portfolios/test_portfolios.py[tag="global-portfolio-code"]

include::example$portfolios/test_portfolios.py[tag="create-portfolio-group"]
----

Now add portfolios to the portfolio group:

include::example$portfolios/test_portfolios.py[tag="add-to-portfolio-group"]
