= Getting Started with LUSID

// {docdatetime}

In this series of guides you will go through the steps to get you connected to LUSID by FINBOURNE, a bi-temporal investment management data platform with portfolio accounting capabilities.

You will need to follow the steps in the following guides:

xref:ROOT:how-to/get-started/create-account.adoc[] ::
Create a LUSID domain and account.

xref:ROOT:how-to/get-started/login-account.adoc[] ::
Login to your LUSID account.

xref:ROOT:how-to/get-started/create-application.adoc[] ::
Create a LUSID application to use with the language SDKs.

But then only follow the steps in one of the guides below, depending on which approach you prefer to take for storing LUSID credentials:

xref:ROOT:how-to/get-started/configure-secrets-file.adoc[] ::
Set up your credentials in a secrets file for use with the language SDKs.

xref:ROOT:how-to/get-started/setup-environment-variables.adoc[] ::
Set up your credentials in environment variables for use with the language SDKs.