= How to get the default transaction types
:description: In this guide we'll learn how to return LUSID's built-in transaction types.

LUSID comes pre-loaded with some commonly used  xref:reference/transaction-types/index.adoc[transaction types].
In this guide you will learn how to return those types.

[NOTE.code]
====
The code and data used in this guide can be downloaded from the {examples-repository}[examples^] section of the LUSID Python Tools repository.
The code is in the {examples-repository-base}/test_configure_transaction_types.py[test_configure_transaction_types.py^] file, and the data under {examples-repository-base}/data/test_configure_transaction_types[data/test_configure_transaction_types^].
====

== Pre Requisites

This guide assumes that you have followed the xref:how-to/connecting-to-lusid/index.adoc[] guides and have successfully connected to LUSID.

== Setup

You will need to import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
----

== Initialise API

Initialise the System Configuration API:

[source, python, indent=0]
----
include::example$transaction-types/test_configure_transaction_types.py[tag="create-apis"]
----

== API call

You can return a list of them by running the following code:

[source, python, indent=0]
----
include::example$transaction-types/test_configure_transaction_types.py[tag="get-transaction-types"]
----

You can see the first two transaction types below:

.Aliases
[format="csv", options="header", cols="15,25,20,20,20"]
|===
include::example$transaction-types/transaction_types_0.csv[]
|===

.Movements
[format="csv", options="header", cols="20,10,10,35,15,10", role="word-wrap"]
|===
include::example$transaction-types/movements_0.csv[]
|===

'''

.Aliases
[format="csv", options="header", cols="15,25,20,20,20"]
|===
include::example$transaction-types/transaction_types_1.csv[]
|===

.Movements
[format="csv", options="header", cols="20,10,10,35,15,10", role="word-wrap"]
|===
include::example$transaction-types/movements_1.csv[]
|===

For a full list of transaction types, see the xref:reference/transaction-types/index.adoc#default-transaction-types[transaction types reference guide].
