= How to load transactions
:description: In this guide we'll learn how to import transactions into LUSID.

In this guide we'll learn how to import xref:reference/transaction.adoc[transactions] into LUSID.

include::partial$ibor-code.adoc[]
== Pre Requisites

This guide assumes that you have followed the xref:how-to/connecting-to-lusid/index.adoc[] guides and have successfully connected to LUSID.
This guide uses the portfolio created in xref:ROOT:how-to/portfolios/create-transaction-portfolio.adoc[], and the instruments loaded in  xref:ROOT:how-to/maintain-instruments-master.adoc[].

== Setup

You will need to import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
include::example$ibor/test_ibor.py[tag="imports-dates"]
----

You can specify your own scope and portfolio codes by updating the line below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="scope"]
include::example$ibor/test_ibor.py[tag="portfolio-code"]
include::example$ibor/test_ibor.py[tag="portfolio-code-shk"]
----

== Initialise API

Initialise the Transactions Portfolio API:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="create-portfolio-api"]
----

== Our Transactions

We have details of transactions, and their accompanying instruments in a CSV file described below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="transactions-file"]
include::example$ibor/test_ibor.py[tag="load-transactions"]
----

.Transactions
[format="csv", options="header", role="word-wrap", cols="10,11,10,12,7,10,10,8,12,10"]
|===
include::example$ibor/transactions.csv[]
|===

[TIP]
====
We are using the built-in transaction types _FundsIn_ and _Buy_.
For a full list of transaction types, see the xref:reference/transaction-types/index.adoc#default-transaction-types[transaction types reference guide].
====

== Import Transactions API Call

You can import transactions using the code below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="import-transactions"]
----

[NOTE]
====
For the transaction that loads cash into our portfolio we need to use a different identifier than for the shares.
For more information about instrument identifiers, see xref:ROOT:how-to/instrument-identifiers.adoc[].
====

If we want to retrieve those transactions, we can do this by following the xref:how-to/transactions/get-transactions.adoc[] guide.
