= How to set holdings of a portfolio

:description: In this guide we'll set the holdings of a transaction portfolio.

In this guide we'll set the xref:reference/holdings.adoc[holdings] of a xref:reference/portfolio/transaction-portfolio.adoc[transaction portfolio].
We might want to do this if we have a set of positions, but don't have transaction data to create those positions.
LUSID will automatically construct adjustment transactions based on the holdings we provide.

[TIP]
====
SetHoldings *replaces a portfolio's current holdings* with the supplied holdings.
Holdings in instruments that are not included in the supplied holdings will be removed (i.e. reduced to zero).
====


include::partial$ibor-code.adoc[]

== Pre Requisites

This guide assumes that you have xref:how-to/portfolios/create-transaction-portfolio-sub-holding-key.adoc[created a transaction portfolio with sub holding key] and imported the instruments described in xref:how-to/maintain-instruments-master.adoc[].

== Setup

Import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
include::example$ibor/test_ibor.py[tag="imports-dates"]
----

You can specify your own scope and portfolio code by updating the line below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="scope"]
include::example$ibor/test_ibor.py[tag="portfolio-code-shk-override"]
----

This guide assumes that you have created a strategy property key, as described below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="sub-holding-key-property"]
include::example$ibor/test_ibor.py[tag="portfolio-with-shk-property-key"]
----

== Initialise API

Initialise the Transaction Portfolios API.

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="create-portfolio-api"]
----

== Data

We have holdings of three instruments stored in the following CSV file:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="holdings-file"]
include::example$ibor/test_ibor.py[tag="load-holdings"]
----

.Holdings
[format="csv", options="header"]
|===
include::example$ibor/holdings.csv[]
|===

From this table, we can see that our portfolio holds 100 units of Amazon stock, 300 units of Apple, and 500 units of CoinBase.

== API calls

=== With sub holding key

To set holdings with a sub holding key, run the following code:

[source, python]
----
include::example$ibor/test_ibor.py[tag="set-holdings-shk", indent=0]
----

=== Without sub holding key

To set holdings without a sub holding key, run the following code:

[source, python]
----
include::example$ibor/test_ibor.py[tag="set-holdings", indent=0]
----

[TIP]
====
If you want to adjust existing holdings, see xref:how-to/holdings/adjust-holdings.adoc[].
For more details on how to view the holdings of a portfolio, see xref:how-to/holdings/view-holdings.adoc[].
====
