= How to view the holdings of a portfolio
:description: In this guide we'll learn how to view holdings in LUSID.

{description}
For more background on holdings, see xref:reference/holdings.adoc[].

include::partial$ibor-code.adoc[]

== Pre Requisites

This guide assumes that you have followed the xref:how-to/connecting-to-lusid/index.adoc[] guides and have successfully connected to LUSID and xref:how-to/connecting-to-lusid/create-api-factory.adoc[created an API factory].
This guide uses the transactions loaded in xref:how-to/load-transactions.adoc[].

== Setup

You will need to import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
include::example$ibor/test_ibor.py[tag="imports-dates"]
----

You can specify your own scope and portfolio code by updating the line below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="scope"]
include::example$ibor/test_ibor.py[tag="portfolio-code"]
----

== Initialise API

Viewing holdings is done using the Transaction Portfolios API.
You can initialise this API end point by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="create-portfolio-api"]
----

== Our Transactions

To recap, these are the transactions that we are basing our holdings on:

.Transactions
[format="csv", options="header"]
|===
include::example$ibor/transactions.csv[]
|===

== Compute holdings

Let's compute holdings based on these transactions.
We'll use the following function to format the response that we get back from the Get Holdings API:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="format-holdings"]
----

=== After funds loaded

We loaded $1,000,000 of funds on 1st January 2020, so let's start by computing our holdings from an hour after we loaded these funds.
You can do this by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-holdings-funds-loaded"]
----

.Holdings after funds loaded
[format="csv", options="header"]
|===
include::example$ibor/holdings_funds_loaded.csv[]
|===

As expected, the only entry is for 1,000,000 USD.

[NOTE]
====
The `Type` returned for this instrument is `B`, which means `Cash Balance`.
For more details on holdings types, see xref:reference/holdings.adoc#holdings-types[What are the holdings types?]
====

=== After first day's trading

Our first day's trading was 2nd January 2020, when we bought 75 units of Amazon at a price of $1902.88 each.
You can compute the holdings after this transaction by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-holdings-first-day-trading"]
----

.Holdings after first day's trading
[format="csv", options="header"]
|===
include::example$ibor/holdings_first_day_trading.csv[]
|===

The amount of GBP has reduced by 142,716 to 857,284, which is exactly the amount of cash that we spent on the Amazon shares.

=== After second day's trading

Our next trades were on 3rd January 2020, when we bought:

* 300 of Apple @ $74.95
* 500 of CoinBase @ $328.28

You can compute the holdings after these transactions by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-holdings-second-day-trading"]
----

.Holdings after second day's trading
[format="csv", options="header"]
|===
include::example$ibor/holdings_second_day_trading.csv[]
|===

We're now down to only $670,659 cash, but we've also got shares in Amazon, Apple, and CoinBase.

=== After all trading

And finally, we can compute our holdings as of 1st February 2020, which will include the purchase of 25 units of Amazon @ $1869.44.
You can see these holdings by running the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-holdings-today"]
----

.Holdings after all trading
[format="csv", options="header"]
|===
include::example$ibor/holdings_today.csv[]
|===

Our cash is now down to $623,923, but our Amazon stock has increased to 100 units at a total cost of $189,452.

=== Filtering by type

We can also filter the holdings by type.
For example, if you only wanted to see holdings of type `Position`, you could run the following code:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="get-holdings-positions"]
----

.Holdings of positions
[format="csv", options="header"]
|===
include::example$ibor/holdings_positions.csv[]
|===
