= How to view the holdings of a portfolio
:description: In this guide we'll learn how to view holdings in LUSID.

In this guide we'll learn how to view the xref:reference/holdings.adoc[holdings] of a xref:reference/portfolio/index.adoc[portfolio] in LUSID.

include::partial$ibor-code.adoc[]

== Pre Requisites

This guide assumes that you have followed the xref:how-to/connecting-to-lusid/index.adoc[] guides and have successfully connected to LUSID and xref:how-to/connecting-to-lusid/create-api-factory.adoc[created an API factory].
This guide uses the transactions loaded in xref:how-to/transactions/load-transactions.adoc[].

== Data

To recap, you should have loaded the following data:

include::partial$transactions.adoc[]

== Setup

You will need to import the following modules into your Python script:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="imports-lusid"]
include::example$ibor/test_ibor.py[tag="imports-pandas"]
include::example$ibor/test_ibor.py[tag="imports-dates"]
----

You can specify your own scope and portfolio code by updating the line below:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="scope"]
include::example$ibor/test_ibor.py[tag="portfolio-code"]
----

== Initialise API

Initialise the Transaction Portfolios API:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="create-portfolio-api"]
----

== API calls

Define the following function to format the response that we get back from the Get Holdings end point:

[source, python, indent=0]
----
include::example$ibor/test_ibor.py[tag="format-holdings"]
----

=== By date

We loaded our initial holdings on 31st December 2019, so let's start by computing our holdings on that day.
You can do this by running the following code:

[source, python]
----
include::example$holdings.py[tag="get-holdings-set-holdings", indent=0]
include::example$ibor/test_ibor.py[tag="get-holdings-set-holdings", indent=0]
----

.Holdings after initial holdings set
[format="csv", options="header"]
|===
include::example$ibor/holdings_set_holdings.csv[]
|===

We can see all our initial holdings.

[NOTE]
====
The `Type` returned for this instrument is `P`, which means `Position`.
For more details on holdings types, see xref:reference/holdings.adoc#holdings-types[What are the holdings types?]
====

We loaded $1,000,000 of funds on 1st January 2020, so let's now compute our holdings from an hour after we loaded these funds.
You can do this by running the following code:

[source, python]
----
include::example$holdings.py[tag="get-holdings-funds-loaded", indent=0]
include::example$ibor/test_ibor.py[tag="get-holdings-funds-loaded", indent=0]
----

.Holdings after funds loaded
[format="csv", options="header"]
|===
include::example$ibor/holdings_funds_loaded.csv[]
|===

As expected, we now have an extra entry for 1,000,000 USD.

We then loaded some transactions on 2nd January 2020, 3rd January 2020, and 4th January 2020.
Let's have a look at our holdings on 1st February 2020, at which points all those transactions have been applied:

[source, python]
----
include::example$holdings.py[tag="get-holdings-today", indent=0]
include::example$ibor/test_ibor.py[tag="get-holdings-today", indent=0]
----

.Holdings after all trading
[format="csv", options="header"]
|===
include::example$ibor/holdings_today.csv[]
|===

We've now doubled the initial holdings that we loaded on 31st December 2019.

=== Filtering by type

We can also filter the holdings by type.
For example, if you only wanted to see holdings of type `Position`, you could run the following code:

[source, python]
----
include::example$holdings.py[tag="get-holdings-positions", indent=0]
include::example$ibor/test_ibor.py[tag="get-holdings-positions", indent=0]
----

.Holdings of positions
[format="csv", options="header"]
|===
include::example$ibor/holdings_positions.csv[]
|===
